# Generated by Django 2.2.1 on 2021-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfood', '0002_food_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=6)),
                ('product_id', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('pref_name', models.CharField(max_length=20, verbose_name='都道府県')),
                ('city_name', models.CharField(max_length=50, verbose_name='市区町村')),
                ('district_name', models.CharField(max_length=50, verbose_name='町丁目')),
            ],
            options={
                'verbose_name': 'カート情報',
                'verbose_name_plural': 'カート情報',
            },
        ),
    ]
