# Generated by Django 2.2.1 on 2021-09-08 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=6, verbose_name='ユーザーID')),
                ('product_id', models.CharField(max_length=6, verbose_name='商品ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
            ],
            options={
                'verbose_name': 'カート情報',
                'verbose_name_plural': 'カート情報',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('gender', models.IntegerField(choices=[(0, '男性'), (1, '女性')], verbose_name='性別')),
                ('mobile', models.CharField(max_length=12, verbose_name='電話番号')),
                ('email', models.CharField(max_length=100, verbose_name='メールアドレス')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー情報データ',
                'verbose_name_plural': 'ユーザー情報データ',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='ワインID')),
                ('thumbnail', models.CharField(max_length=50, verbose_name='サムネイル')),
                ('name', models.CharField(max_length=50, verbose_name='ワイン名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stock', models.IntegerField(verbose_name='在庫')),
                ('harvest_year', models.IntegerField(verbose_name='収穫年')),
                ('producer', models.CharField(max_length=50, verbose_name='生産者')),
                ('region', models.CharField(max_length=50, verbose_name='産地')),
                ('style', models.CharField(max_length=20, verbose_name='タイプ')),
                ('type', models.CharField(max_length=50, verbose_name='品種')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WineOpener.Profile', verbose_name='所有者')),
            ],
            options={
                'verbose_name': '販売ワインデータ',
                'verbose_name_plural': '販売ワインデータ',
            },
        ),
    ]
