# Generated by Django 2.2.1 on 2021-09-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WineOpener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=6, verbose_name='ユーザーID')),
                ('stream_id', models.CharField(max_length=6, verbose_name='コメントID')),
                ('comment', models.CharField(max_length=50, verbose_name='コメント')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
                'db_table': 'topic',
                'managed': True,
            },
        ),
    ]
