"""
Django settings for WineOpener_proj project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fdazr+8mmkg24cwav5ufs#0cac-in!ls$4+jshts4xcoe%t&dq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["35.76.198.115", "wineopener.techpreneur.jp"]

# Application definition 
INSTALLED_APPS = [ 
    'django.contrib.admin', # 管理サイト
    'django.contrib.auth', # 認証管理
    'django.contrib.contenttypes', #コンテンツタイプ
    'django.contrib.sessions', #セッション管理
    'django.contrib.messages', #メッセージ管理
    'django.contrib.staticfiles', #静的ファイル管理
    'WineOpener', # WineOpenerを追加（2021/09/04）
    'bootstrap4', # 追加(2021/09/06)
    'mathfilters', # 追加(2021/09/07)
    'stripe', # 追加(2021/09/09)
    'rest_framework', # 追加(2021/09/09)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WineOpener_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins':[ 
                'bootstrap4.templatetags.bootstrap4' #追加(2021/09/06)
            ],
        },
    },
]

WSGI_APPLICATION = 'WineOpener_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    [
        os.path.join(BASE_DIR, "static"),
    ]
)

LOGIN_URL='/accounts/login'
LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL='/'

STRIPE_PUBLISHABLE_KEY = 'pk_test_51JSsEIFHEQ8jpLAoaplG1M3ku0hb12xdVDaGSZ1FUth16HXnXtt4LDUlOnbLdukmFRmb5NNEzcP7GJpjlcVmS9PY00kLJWs58V'
STRIPE_SECRET_KEY = 'sk_test_51JSsEIFHEQ8jpLAoL6sjCZ9zwUJQa6rSlx24lUlsWMAywzEYjRIPBT4PTSMkfTAZKUZelnII9NKAxGnrXMPxim2S00Qh2eBpl4'