# Generated by Django 2.2.1 on 2021-08-26 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wineopener', '0003_scorelog_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=6)),
                ('product_id', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='追加日時')),
            ],
            options={
                'verbose_name': 'カート情報',
                'verbose_name_plural': 'カート情報',
            },
        ),
    ]
