# Generated by Django 2.2.1 on 2021-08-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineopener', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='追加日時'),
        ),
    ]
